[build]
rustflags = [
    "-A", "dead_code",
    "-A", "unused_variables",
    "-A", "unused_imports",
    "-A", "non_snake_case",
    "-A", "non_camel_case_types",
    "-A", "non_upper_case_globals"
]
